---
movies:
  buildRepo: false
  breakdown:
    -
      year: 2015
      titles:
        - The Revenant
        - "Star Wars: Episode VII"
        - The Hateful Eight
        - Spotlight
        - The Martian
        - The Big Short
        - Room
        - Hardcore Henry
        - Bridge of Spies
        - Spectre
        - Sicario
        - The Danish Girl
        - Legend
        - "Mad Max: Fury Road"
        - Creed
        - GooseBumps
        - The Last Witch Hunter
        - The Witch
        - The Good Dinosaur
        - "Avengers: Age of Ultron"
        - Black Mass
        - Ex Machina
    -
      year: 2014
      titles:
        - Interstellar
        - "Kingsman: The Secret Service"
        - Guardians of the Galaxy
        - Gone Girl
        - John Wick
        - Whiplash
        - "X-men: Days of Future Past"
        - The Imitation Game
        - "Birdman or (The Unexpected Virtue of Ignorance)"
        - The Theory of Everything
        - The Grand Budapest Hotel
        - Fury

